### ISSUE TITLE
Debug-Client-0.31: Error:  given is deprecated at ... on Strawberry Perl 3.38.0

### ISSUE THREAD

**Issue by twata1** [PadreIDE/Debug-Client#13]
Hello,

Running Strawberry Perl 5.38.0, I noticed the following message.

```
C:\home\skyfish>cpan MANWAR/Debug-Client-0.31.tar.gz

(snip)

t/00-report-prereqs.t .. ok

#   Failed test 'use Debug::Client;'
#   at t/01-compile.t line 10.
#     Tried to use 'Debug::Client'.
#     Error:  given is deprecated at C:\strawberry-perl-5.38.0.1-64bit-portable\cpan\build\Debug-Client-0.31-1\blib\lib/Debug/Client.pm line 237.
# Compilation failed in require at t/01-compile.t line 10.
# BEGIN failed--compilation aborted at t/01-compile.t line 10.
Use of uninitialized value $Debug::Client::VERSION in concatenation (.) or string at t/01-compile.t line 32.
# Looks like your test exited with 255 just after 18.
t/01-compile.t .........
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/18 subtests

#   Failed test 'use Debug::Client;'
#   at t/02-exports.t line 10.
#     Tried to use 'Debug::Client'.
#     Error:  given is deprecated at C:\strawberry-perl-5.38.0.1-64bit-portable\cpan\build\Debug-Client-0.31-1\blib\lib/Debug/Client.pm line 237.
# Compilation failed in require at t/02-exports.t line 10.
# BEGIN failed--compilation aborted at t/02-exports.t line 10.

#   Failed test 'Debug::Client->can(...)'
#   at t/02-exports.t line 24.
#     Debug::Client->can('get_filename') failed
#     Debug::Client->can('get') failed
#     Debug::Client->can('get_h_var') failed
#     Debug::Client->can('get_options') failed
#     Debug::Client->can('get_p_exp') failed
#     Debug::Client->can('get_v_vars') failed
#     Debug::Client->can('get_value') failed
#     Debug::Client->can('get_x_vars') failed
#     Debug::Client->can('get_y_zero') failed
#     Debug::Client->can('module') failed
#     Debug::Client->can('remove_breakpoint') failed
#     Debug::Client->can('get_row') failed
#     Debug::Client->can('set_breakpoint') failed
#     Debug::Client->can('set_option') failed
#     Debug::Client->can('show_breakpoints') failed
# Looks like you failed 2 tests of 2.
t/02-exports.t .........
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/2 subtests
t/03-pod.t ............. skipped: Author tests, not required for installation.
t/04-pod-coverage.t .... skipped: Author tests, not required for installation.

(snip)

```

Thank you,

**Comment by szabgab** [comment]
thanks for reporting

**Comment by viy2** [comment]
patch for given ... when

**Comment by viy2** [comment]
--- perl-Debug-Client-0.31/eg/debugger.pl	2017-12-19 19:33:14.000000000 +0200
+++ perl-Debug-Client-0.31/eg/debugger.pl	2023-12-06 17:36:04.550178142 +0200
@@ -77,44 +77,42 @@
 		$input = $last_step;
 	}
 
-	given ($input) {
-		when ( [ 'h', '?' ] ) {
-			help();
-		}
-		when ('s') {
-			$last_step = 's';
-			my $out = $debugger->step_in;
-			print $out;
-		}
-		when ('n') {
-			$last_step = 'n';
-			my $out = $debugger->step_over;
-			print $out;
-		}
-		when ('r') {
-			my $out = $debugger->step_out;
-			print $out;
-		}
-		when ('T') {
-			my $out = $debugger->get_stack_trace;
-			print $out;
-		}
-		when ('.') {
-			my $out = $debugger->show_line;
-			print $out;
-		}
-		when ('q') {
-			last;
-		}
-		when (qr/^c   (?:\s+(\w+))?  $/x) {
-			my $out = $debugger->run($1);
-			print $out;
-		}
-		default {
-			#my $out = $debugger->execute_code($input);
-			#print $out;
-			print "Invalid command\n";
-		}
+	if ($input eq 'h' or $input eq '?') {
+		help();
+	}
+	elsif ($input eq 's') {
+		$last_step = 's';
+		my $out = $debugger->step_in;
+		print $out;
+	}
+	elsif ($input eq 'n') {
+		$last_step = 'n';
+		my $out = $debugger->step_over;
+		print $out;
+	}
+	elsif ($input eq 'r') {
+		my $out = $debugger->step_out;
+		print $out;
+	}
+	elsif ($input eq 'T') {
+		my $out = $debugger->get_stack_trace;
+		print $out;
+	}
+	elsif ($input eq '.') {
+		my $out = $debugger->show_line;
+		print $out;
+	}
+	elsif ($input eq 'q') {
+		last;
+	}
+	elsif ($input =~ /^c\s+(\w+)$/x) {
+		my $out = $debugger->run($1);
+		print $out;
+	}
+	else {
+		# my $out = $debugger->execute_code($input);
+		# print $out;
+		print "Invalid command\n";
 	}
 }
 
--- perl-Debug-Client-0.31/lib/Debug/Client.pm	2017-12-19 19:33:14.000000000 +0200
+++ perl-Debug-Client-0.31/lib/Debug/Client.pm	2023-12-06 17:32:26.361800306 +0200
@@ -233,28 +233,26 @@
 
 	$self->_prompt;
 
+	my $buffer = $self->{buffer};
 	# if it was successful no reply
-	given ( $self->{buffer} ) {
-		when ( $_ =~ /^Subroutine [\w:]+ not found[.]/sxm ) {
-			return 0;
-		}
-		when ( $_ =~ /^Line \d+ not breakable[.]/sxm ) {
-			return 0;
-		}
-		when ( $_ =~ /^\d+ levels deep in subroutine calls!/sxm ) {
-			return 0;
-		}
-		when ( $_ =~ /^Already in/m ) {
-			return 1;
-		}
-		when ( $_ =~ /\S/sxm ) {
-
-			# say 'Non-whitespace charter found';
-			return 0;
-		}
-		default {
-			return 1;
-		}
+	if ( $buffer =~ /^Subroutine [\w:]+ not found[.]/sxm ) {
+		return 0;
+	}
+	elsif ( $buffer =~ /^Line \d+ not breakable[.]/sxm ) {
+		return 0;
+	}
+	elsif ( $buffer =~ /^\d+ levels deep in subroutine calls!/sxm ) {
+		return 0;
+	}
+	elsif ( $buffer =~ /^Already in/m ) {
+		return 1;
+	}
+	elsif ( $buffer =~ /\S/sxm ) {
+		# say 'Non-whitespace character found';
+		return 0;
+	}
+	else {
+		return 1;
 	}
 }

**Comment by viy2** [comment]
[perl-Debug-Client-0.31-perl5.38-no-given-when.patch.gz](https://github.com/PadreIDE/Debug-Client/files/13588348/perl-Debug-Client-0.31-perl5.38-no-given-when.patch.gz)

**Comment by eserte** [comment]
With perl 5.41.x and the removal of switch and smartmatch, this is now fatal:
```
#   Failed test 'use Debug::Client;'
#   at t/01-compile.t line 10.
#     Tried to use 'Debug::Client'.
#     Error:  syntax error at /home/cpansand/.cpan/build/2024102011/Debug-Client-0.31-0/blib/lib/Debug/Client.pm line 237, near ") {"
# Execution of /home/cpansand/.cpan/build/2024102011/Debug-Client-0.31-0/blib/lib/Debug/Client.pm aborted due to compilation errors.
# Compilation failed in require at t/01-compile.t line 10.
# BEGIN failed--compilation aborted at t/01-compile.t line 10.
Use of uninitialized value $Debug::Client::VERSION in concatenation (.) or string at t/01-compile.t line 32.
# Looks like your test exited with 255 just after 18.
t/01-compile.t ......... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/18 subtests 
```

**Comment by szabgab** [comment]
0.32 released fixing this. Thanks for the reports.
