### ISSUE TITLE
Build fails under 5.24.1 and others

### ISSUE THREAD

**Issue by TBSliver** [PadreIDE/Debug-Client#4]
Debug::Client fails to install under a 5.24.1 install on Debian - as well as many others it seems according ot the CPAN Testers matrix: http://matrix.cpantesters.org/?dist=Debug-Client+0.29

This all seems to be t/24-y_zero.t. Full build log output here: [build.log](https://github.com/PadreIDE/Debug-Client/files/796315/build.log.txt)

However a fix for this seems to be mentioned in #2 - will try that and report back.

**Comment by TBSliver** [comment]
Yep the fix in #2 works in Debian, would reccomend taking that patch.

**Comment by manwar** [comment]
Patch released.
